### PR TITLE
`feat`: update colors, added install/remove menus, fixed issue where powershell did not work.

### PR DESCRIPTION
**Pull request by lezetho**
it adds more and (i believe) more compatibility. also solves the `temp` error where it would try to rm the whole temp folder.

### CODE REVIEW

**Comment by lezetho** [comment]
Screenshots:

image
image
image
image
image
image

**Comment by Arhznblaster** [comment]
Merged.

**Comment by Arhznblaster** [comment]
Merged.

**Comment by lezetho** [comment]
jejeje

**Pull request closed without merging**
